= LeagueTrollBuild Angular Frontend

This project was generated with https://github.com/angular/angular-cli[Angular CLI].

== Development server

Run `npm run start` for a dev server running the troll build project. Navigate to `http://localhost:4200/`.

Run `npm run start-admin` for a dev server running the troll build admin project. Navigate to `http://localhost:4201/`

The apps will automatically reload if you change any of the source files.

== Code scaffolding

Run `ng generate <project> component component-name` to generate a new component.
You can also use `ng generate <project> directive|pipe|service|class|guard|interface|enum|module`.

== Build

Run `npm run build-all` to build the troll build and admin projects. The build artifacts will be stored in the `dist/`
directory. They will use the `--prod` flag for a production build.

== Running unit tests

Run `ng test-all` to execute the unit tests via https://karma-runner.github.io[Karma].

== Running end-to-end tests
First ensure PostgreSQL is running.

Then start the backend either with Gradle: `./gradlew bootRun` or in your IDE.

NOTE: e2e tests assume the backend already has data from Riot in the database. If missing data, run the All Retrievals job prior.

Otherwise you'll see `Error occurred while trying to proxy request` and most tests will fail.

Run `ng e2e-all` to execute the end-to-end tests via http://www.protractortest.org/[Protractor].

== Further help

To get more help on the Angular CLI use `ng help` or go check out the https://github.com/angular/angular-cli/blob/master/README.md[Angular CLI README].
