= LeagueTrollBuild

League Troll Build is a random build generator (hence the terms "troll build") for playable Champions of the popular
online game: http://leagueoflegends.com/[League of Legends].

= Technology stack, frameworks, and third-party libraries
* http://www.oracle.com/technetwork/java/javase/overview/java8-2100321.html[Java 8] with https://projectlombok.org/[Lombok]
* https://github.com/gradle/gradle[Gradle]
* https://github.com/spring-projects/spring-boot[Spring Boot]
* https://github.com/spring-projects/spring-data-jpa[Spring Data JPA] with https://github.com/hibernate/hibernate-orm[Hibernate]
* https://github.com/spring-projects/spring-data-rest[Spring Data REST]
* https://github.com/spring-projects/spring-security[Spring Security]
* http://www.postgresql.org/[PostgreSQL] or https://github.com/h2database/h2database[H2]
* https://github.com/flyway/flyway[Flyway]
* https://github.com/ehcache[EhCache]
* https://github.com/thymeleaf/thymeleaf[Thymeleaf]
* http://www.webjars.org/[Webjars]
* https://github.com/Semantic-Org/Semantic-UI[Semantic UI]
* https://github.com/DataTables/DataTablesSrc[DataTables]

= Profiles
`LeagueTrollBuild` provides four profiles:

external::
Production profile that is active by default and uses PostgreSQL along with environment variables to specify the
database credentials. Use the `DB_USERNAME`, `DB_PASSWORD`, `DB_URL` environment variables for the database credentials.

embedded::
Secondary production profile that uses an embedded H2 for quickly running the app locally without a PostgreSQL install.

dev::
Development profile that also uses PostgreSQL but neither caches message properties nor Thymeleaf's HTML templates.

test::
Testing profile for https://github.com/junit-team/junit[JUnit 4] tests.

To override an active profile, set the `spring.profiles.active` argument property such as:

 -Dspring.profiles.active=dev

Or using the environment variable `SPRING_PROFILES_ACTIVE`. Otherwise, the `external` profile will be active.

= Riot API Key
An API key provided from Riot is required to use https://developer.riotgames.com/[Riot's API].

When running `LeagueTrollBuild`, the API key is supplied using the `RIOT_API_KEY` environment variable or the
`-Driot.api.key` argument property. If the API key is not supplied, the configuration properties validation will fail
and thus the app will not start (by design).

= Running locally
*Note*, a Java 8 JRE is required.

First, download or clone the project. With the project saved locally, one may either:

Run the app using Gradle:

 gradlew -Dspring.profiles.active=PROFILE_OVERRIDE -Driot.api.key=API_KEY_IF_NOT_ENV_VAR

Or `build` the project as a `jar` using Gradle and run with `java`:

To do so, build the project first using Gradle:

 gradlew build

Next, `cd` to the `build/libs` folder in the project root and then run directly using `java`:

 java -jar -Dspring.profiles.active=PROFILE_OVERRIDE -Driot.api.key=API_KEY_IF_NOT_ENV_VAR LeagueTrollBuild-VERSION.jar

From either method and with the project running, view http://localhost:8080/[localhost:8080] on your browser.

= Development/Importing the project
*Note*, a Java 8 JDK is required.

`LeagueTrollBuild` is developed using the https://www.jetbrains.com/idea/[IntelliJ IDEA] IDE.

If using IntelliJ, one must first download the https://plugins.jetbrains.com/plugin/6317[Lombok plugin] and
`Enable annotation processing` in the `Annotation Processors` of the main settings. Then import the project from the
`build.gradle`.

If using Eclipse, one must first install the Lombok plugin manually using the `lombok.jar` and install the
https://marketplace.eclipse.org/content/gradle-integration-eclipse-0[Gradle Integration plugin] from the Eclipse
Marketplace. Then import the project as a Gradle project.

= License
`LeagueTrollBuild` is licensed under the MIT License (MIT).