= LeagueTrollBuild

League Troll Build is a random, shareable build generator (hence the term "troll build") for playable Champions of
the popular online game: http://leagueoflegends.com/[League of Legends].

== Tech stack, frameworks, and libraries
* https://openjdk.java.net/projects/jdk/17/[Java 17]
* https://github.com/gradle/gradle[Gradle]
* https://github.com/spring-projects/spring-boot[Spring Boot]
* https://github.com/angular/angular[Angular]
* https://github.com/spring-projects/spring-data-jpa[Spring Data JPA] with https://github.com/hibernate/hibernate-orm[Hibernate]
* https://github.com/spring-projects/spring-security[Spring Security]
* https://github.com/spring-projects/spring-restdocs[Spring REST Docs]
* https://github.com/spring-projects/spring-batch[Spring Batch]
* http://www.postgresql.org/[PostgreSQL] or https://github.com/h2database/h2database[H2]
* https://github.com/flyway/flyway[Flyway]
* https://github.com/ehcache[EhCache]
* https://github.com/akveo/nebular/[Nebular]
* https://github.com/vmware/clarity/[Clarity]

== Running the Backend locally
See https://github.com/drumonii/LeagueTrollBuild/tree/master/backend[README] in the `backend` module

== Running the Frontend locally
See https://github.com/drumonii/LeagueTrollBuild/tree/master/frontend[README] in the `frontend` module

== Development Prerequisites
* Java 17 JDK
* Node 14 or later

== Building
To build the project as a `jar` that includes the built Angular frontend bundle as a static resource
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-static-content[served by Spring Boot]:

  ./gradlew build

NOTE: You may skip tests by appending the `-x test` argument for a quicker build.

Once gradle has finished with `BUILD SUCCESSFUL`:

  cd build

Then run using `java -jar`

  java -jar league-troll-build.jar

Optionally, you can use the `embedded` profile override with:

  java -jar -Dspring.profiles.active=embedded league-troll-build.jar

Once the app starts, view http://localhost:8080[localhost:8080] on your browser.

== Docker
Instead of building and running the project manually, you can use Docker to do that. This assumes you have Docker already installed.

From the root of the project, first build the image:

  docker build -t league-troll-build:latest .

Next run the container:

  docker run --name league-troll-build --publish 8080:8080 --detach league-troll-build:latest

The app will retrieve the latest data from Riot. Once completed, view http://localhost:8080[localhost:8080] on your browser.

== License
`LeagueTrollBuild` is licensed under the MIT License (MIT).
