= LeagueTrollBuild

League Troll Build is a random, shareable build generator (hence the terms "troll build") for playable Champions of
the popular online game: http://leagueoflegends.com/[League of Legends].

== Tech stack, frameworks, and libraries
* http://www.oracle.com/technetwork/java/javase/overview/java8-2100321.html[Java 8] with https://projectlombok.org/[Lombok]
* https://github.com/gradle/gradle[Gradle]
* https://github.com/spring-projects/spring-boot[Spring Boot]
* https://github.com/angular/angular[Angular]
* https://github.com/spring-projects/spring-data-jpa[Spring Data JPA] with https://github.com/hibernate/hibernate-orm[Hibernate]
* https://github.com/spring-projects/spring-security[Spring Security]
* https://github.com/spring-projects/spring-restdocs[Spring REST Docs]
* https://github.com/spring-projects/spring-batch[Spring Batch]
* http://www.postgresql.org/[PostgreSQL] or https://github.com/h2database/h2database[H2]
* https://github.com/flyway/flyway[Flyway]
* https://github.com/ehcache[EhCache]
* http://www.webjars.org/[Webjars] with https://github.com/wro4j/wro4j[Wro4j]
* https://github.com/DataTables/DataTablesSrc[DataTables]
* https://github.com/metafizzy/isotope[Isotope]

== Profiles
`LeagueTrollBuild` provides four database profiles:

external::
Production profile that is active by default and uses PostgreSQL along with environment variables to specify the
database credentials. Use the `DB_USERNAME`, `DB_PASSWORD`, `DB_URL` environment variables for the database credentials.

embedded::
Secondary production profile that uses an embedded H2 for quickly running the app locally without a PostgreSQL install.

dev::
Development profile that also uses PostgreSQL but neither caches message properties nor Thymeleaf's HTML templates.

test::
Testing profile for https://github.com/junit-team/junit[JUnit 4] tests.

In addition, there are two Riot API profiles:

static-data::
lol-static-data-v3

ddragon::
Data Dragon

To override an active profile, set the `spring.profiles.active` argument property such as:

 -Dspring.profiles.active=dev,static-data

Or using the environment variable `SPRING_PROFILES_ACTIVE`. Otherwise, if a profile is not specified, the `external`
and `ddragon` profiles will be active.

== Riot API Key
An https://developer.riotgames.com/api-keys.html[API key] provided from Riot is required to use https://developer.riotgames.com/api-methods/#lol-static-data-v3[lol-static-data-v3].

When running `LeagueTrollBuild` with the `static-data` profile, the API key is supplied using the `RIOT_STATICDATA_APIKEY` environment
variable or the `-Driot.static-data.apiKey` argument property. If the API key is not supplied, the configuration properties validation
will fail and thus the app will not start (by design).

If running `LeagueTrollBuild` with the `ddragon` profile, no API key is required.

== Running locally
*Note*, a Java 8 JRE is required. Previous JREs are not supported.

First, download or clone the project. With the project saved locally, one may either:

Run the app using Gradle:

 gradlew -Dspring.profiles.active=PROFILE_OVERRIDE

Or `build` the project as a `jar` using Gradle and run with `java`:

To do so, build the project first using Gradle:

 gradlew build

Next, `cd` to the `build/libs` folder in the project root and then run directly using `java`:

 java -jar -Dspring.profiles.active=PROFILE_OVERRIDE LeagueTrollBuild-VERSION.jar

From either method and with the project running, view http://localhost:8080/[localhost:8080] on your browser.

=== All Retrievals from Riot
Optionally, run with the following argument properties to trigger on startup the retrieval of the latest data (Items,
 Maps, Champions, Summoner Spells) from Riot's API in order to perform a troll build of a Champion.

  -Dspring.batch.job.enabled=true -Dspring.batch.job.names=allRetrievalsJob

This is useful to avoid manual saving of data through the admin area. If data already exists in the database, a new
patch is out, and the retrievals job is run, then new data will be saved and absent data will be deleted.

=== API Documentation
To view the generated API guide, visit http://localhost:8080/docs/api-guide.html[localhost:8080/docs/api-guide.html].

To generate the API Documentation locally, run the asciidoctor Gradle task with the single test `ApiDocumentation`:

  asciidoctor -Dtest.single=ApiDocumentation

Then navigate to `/build/asciidoc/html5/api-guide.html` to view the generated API guide.

== Development/Importing the project
*Note*, a Java 8 JDK is required. Previous JDKs are not supported.

`LeagueTrollBuild` is developed using the https://www.jetbrains.com/idea/[IntelliJ IDEA] IDE.

If using IntelliJ, one must first download the https://plugins.jetbrains.com/plugin/6317[Lombok plugin] and
`Enable annotation processing` in the `Annotation Processors` of the main settings. Then import the project from the
`build.gradle`.

If using Eclipse, one must first install the Lombok plugin manually using the `lombok.jar` and install the
https://marketplace.eclipse.org/content/gradle-integration-eclipse-0[Gradle Integration plugin] from the Eclipse
Marketplace. Then import the project as a Gradle project.

In addition, one must specify the Riot API key either as an argument property or environment variable when creating a
run configuration in the IDE.

== License
`LeagueTrollBuild` is licensed under the MIT License (MIT).