= LeagueTrollBuild

League Troll Build is a random, shareable build generator (hence the terms "troll build") for playable Champions of
the popular online game: http://leagueoflegends.com/[League of Legends].

== Tech stack, frameworks, and libraries
* https://openjdk.java.net/projects/jdk/10/[Java 10]
* https://github.com/gradle/gradle[Gradle]
* https://github.com/spring-projects/spring-boot[Spring Boot]
* https://github.com/angular/angular[Angular 7]
* https://github.com/spring-projects/spring-data-jpa[Spring Data JPA] with https://github.com/hibernate/hibernate-orm[Hibernate]
* https://github.com/spring-projects/spring-security[Spring Security]
* https://github.com/spring-projects/spring-restdocs[Spring REST Docs]
* https://github.com/spring-projects/spring-batch[Spring Batch]
* http://www.postgresql.org/[PostgreSQL] or https://github.com/h2database/h2database[H2]
* https://github.com/flyway/flyway[Flyway]
* https://github.com/ehcache[EhCache]
* https://github.com/jgthms/bulma[Bulma]

== Running the Backend locally
See https://github.com/drumonii/LeagueTrollBuild/tree/master/backend[README] in the `backend` module

== Running the Frontend locally
See https://github.com/drumonii/LeagueTrollBuild/tree/master/frontend[README] in the `frontend` module

== Development Prerequisites
* Java 10 JDK
* Node >= 10.9.0
* Npm >= 6.4.1

== Building
To build the project as a `jar` that includes the built Angular frontend bundle as a static resource
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-static-content[served by Spring Boot]:

  ./gradlew build

Once gradle has finished with `BUILD SUCCESSFUL`:

  cd backend/build/libs

Then run using `java -jar`

  java -jar league-troll-build-APP_VERSION.jar

Optionally, you can provide a profile override with:

  java -jar -Dspring.profiles.active=YOUR_PROFILE_OVERRIDE league-troll-build-APP_VERSION.jar

Once the app starts, view http://localhost:8080[localhost:8080] on your browser.

== License
`LeagueTrollBuild` is licensed under the MIT License (MIT).
