= LeagueTrollBuild

League Troll Build is a random, shareable build generator (hence the terms "troll build") for playable Champions of
the popular online game: http://leagueoflegends.com/[League of Legends].

== Tech stack, frameworks, and libraries
* https://www.oracle.com/java/java9.html[Java 9] with https://projectlombok.org/[Lombok]
* https://github.com/gradle/gradle[Gradle]
* https://github.com/spring-projects/spring-boot[Spring Boot]
* https://github.com/angular/angular[Angular 6]
* https://github.com/spring-projects/spring-data-jpa[Spring Data JPA] with https://github.com/hibernate/hibernate-orm[Hibernate]
* https://github.com/spring-projects/spring-security[Spring Security]
* https://github.com/spring-projects/spring-restdocs[Spring REST Docs]
* https://github.com/spring-projects/spring-batch[Spring Batch]
* http://www.postgresql.org/[PostgreSQL] or https://github.com/h2database/h2database[H2]
* https://github.com/flyway/flyway[Flyway]
* https://github.com/ehcache[EhCache]
* https://github.com/jgthms/bulma[Bulma]

== Running the Backend locally
See README in the `backend` module

== Running the Frontend locally
See README in the `frontend` module

== Development/Importing the project
Prerequisites:

* Java 9 JDK
* Node 8.11.x
* Npm ~5.8.0

`LeagueTrollBuild` is developed using the https://www.jetbrains.com/idea/[IntelliJ IDEA] IDE.

If using IntelliJ, one must first download the https://plugins.jetbrains.com/plugin/6317[Lombok plugin] and
`Enable annotation processing` in the `Annotation Processors` of the main settings. Then import the project from the
`build.gradle`.

If using Eclipse, one must first install the Lombok plugin manually using the `lombok.jar` and install the
https://marketplace.eclipse.org/content/gradle-integration-eclipse-0[Gradle Integration plugin] from the Eclipse
Marketplace. Then import the project as a Gradle project.

== Building
To build the project as a `jar` that includes the built Angular frontend bundle as a static resource
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-static-content[served by Spring Boot]:

  ./gradlew build

Once gradle has finished with `BUILD SUCCESSFUL`:

  cd backend/build/libs

Then run using `java -jar`

  java -jar -Dspring.profiles.active=YOUR_PROFILE_OVERRIDE league-troll-build-APP_VERSION.jar

Once the app starts, view http://localhost:8080[localhost:8080] on your browser.

== License
`LeagueTrollBuild` is licensed under the MIT License (MIT).
