# ======================
# Troll Build Properties
# ======================

riot:
  static-data:
    apiKey: # from RIOT_STATICDATA_APIKEY environment variable or -Driot.staticdata.apiKey argument property
    base-url: "{region}.api.riotgames.com/lol/static-data/v3"
    keyParam: api_key
    localeParam: locale
    locale: en_US
    region: na1
    champions: /champions
    champion: /champions/{id}
    items: /items
    item: /items/{id}
    maps: /maps
    summoner-spells: /summoner-spells
    summoner-spell: /summoner-spells/{id}
    versions: /versions
  ddragon:
    base-url: ddragon.leagueoflegends.com
    locale: en_US
    champions: /cdn/{version}/data/{locale}/champion.json
    champion: /cdn/{version}/data/{locale}/champion/{id}.json
    champions-img: /cdn/{version}/img/champion/{championImgFull}
    champions-spell-img: /cdn/{version}/img/spell/{championSpellImgFull}
    champions-passive-img: /cdn/{version}/img/passive/{championPassiveImgFull}
    items: /cdn/{version}/data/{locale}/item.json
    items-img: /cdn/{version}/img/item/{itemImgFull}
    maps: /cdn/{version}/data/{locale}/map.json
    maps-img: /cdn/{version}/img/map/{mapImgFull}
    summoner-spells: /cdn/{version}/data/{locale}/summoner.json
    summoner-spells-img: /cdn/{version}/img/spell/{summonerSpellImgFull}
    versions: /api/versions.json

# ======================
# Spring Boot Properties
# ======================

spring:
  # Spring active profile
  profiles.active: external, ddragon
  # Data REST base URI
  data.rest.base-path: /api
  # Internalization
  messages.basename: i18n/messages
  # Thymeleaf
  thymeleaf.mode: HTML
  # Batch
  batch:
    initialize-schema: never
    job:
      enabled: false
  # Jackson
  jackson:
    deserialization:
      fail_on_unknown_properties: false
# Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /admin/actuator
      exposure:
        include: env, flyway, health, metrics
#Wro4j
wro4j:
  filter-url: /assets
  manager-factory:
    pre-processors: cssMinJawr, jsMin
  debug: false

---

# Production profile with an embedded H2 database
spring:
  profiles: embedded
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:
        temp.use_jdbc_metadata_defaults: false

---

# Production profile with an external PostgreSQL database
spring:
  profiles: external
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: false
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:
        temp.use_jdbc_metadata_defaults: false

---

# Development profile with a local PostgreSQL database
spring:
  profiles: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/loltrollbuild
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: true
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:
        temp.use_jdbc_metadata_defaults: false
#Wro4j
wro4j:
  resource-watcher-update-period: 5

---

# Unit testing profile with an embedded H2 database
spring:
  profiles: testing
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:
        temp.use_jdbc_metadata_defaults: false
  # Cache
  cache:
    type: simple
