# ======================
# Troll Build Properties
# ======================

riot:
  api:
    key: # Riot API key goes here
    static-data:
      base-url: global.api.pvp.net/api/lol/static-data/{region}/v1.2
      param: api_key
      region: na
      scheme: https
      champions:  /champion
      items: /item
      summoner-spells: /summoner-spell
