# ======================
# Troll Build Properties
# ======================

riot:
  api:
    key: # from RIOT_API_KEY environment variable or -Driot.api.key argument property
    static-data:
      base-url: "{region}.api.riotgames.com/lol/static-data/v3"
      keyParam: api_key
      region: na1
      scheme: https
      champions:  /champions
      champion:  /champions/{id}
      items: /items
      item: /items/{id}
      maps: /maps
      summoner-spells: /summoner-spells
      summoner-spell: /summoner-spells/{id}
      versions: /versions
    ddragon:
      base-url: ddragon.leagueoflegends.com/cdn
      scheme: https
      champions-img: /{version}/img/champion/{championImgFull}
      champions-spell-img: /{version}/img/spell/{championSpellImgFull}
      champions-passive-img: /{version}/img/passive/{championPassiveImgFull}
      items-img: /{version}/img/item/{itemImgFull}
      maps-img: /{version}/img/map/{mapImgFull}
      summoner-spells-img: /{version}/img/spell/{summonerSpellImgFull}

# ======================
# Spring Boot Properties
# ======================

spring:
  # Spring active profile
  profiles.active: external
  # Data REST base URI
  data.rest.base-path: /api
  # Internalization
  messages.basename: i18n/messages
  # Thymeleaf
  thymeleaf.mode: HTML
  # Batch
  batch:
    initializer.enabled: false
    job.enabled: false
  # Jackson
  jackson:
    serialization:
      write_dates_as_timestamps: false
# Actuator
management:
  context-path: /admin/actuator
  security:
    roles: ADMIN
#Wro4j
wro4j:
  filter-url: /assets
  manager-factory:
    pre-processors: cssMinJawr, jsMin
  debug: false

---

# Production profile with an embedded H2 database
spring:
  profiles: embedded
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:

---

# Production profile with an external PostgreSQL database
spring:
  profiles: external
  datasource:
    initialize: false
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: false
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:

---

# Development profile with a local PostgreSQL database
spring:
  profiles: dev
  datasource:
    initialize: false
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/loltrollbuild
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: true
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:

#Wro4j
wro4j:
  resource-watcher-update-period: 5

---

# Unit testing profile with an embedded H2 database
spring:
  profiles: testing
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:
