# ======================
# Troll Build Properties
# ======================

riot:
  api:
    key: # Riot API key goes here
    static-data:
      base-url: global.api.pvp.net/api/lol/static-data/{region}/v1.2
      param: api_key
      region: na
      scheme: https
      champions:  /champion
      champion:  /champion/{id}
      items: /item
      item: /item/{id}
      summoner-spells: /summoner-spell
      summoner-spell: /summoner-spell/{id}
      versions: /versions
    ddragon:
      base-url: ddragon.leagueoflegends.com/cdn
      scheme: http
      champions-img: /{version}/img/champion/{championImgFull}
      items-img: /{version}/img/item/{itemImgFull}
      summoner-spells-img: /{version}/img/spell/{summonerSpellImgFull}

# ======================
# Spring Boot Properties
# ======================

spring:
  # Spring active profile
  profiles.active: embedded
  # Data REST base URI
  data.rest.base-uri: /api
  # Internalization
  messages.basename: i18n/messages

---

# Production profile with an embedded H2 database
spring:
  profiles: embedded
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: true
        generate_statistics: false
        hbm2ddl.auto:

---

# Production profile with an external PostgreSQL database
spring:
  profiles: external
  datasource:
    initialize: false
    jndi-name: jdbc/leagueTrollBuild
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: false
        format_sql: true
        generate_statistics: false
        hbm2ddl.auto:

---

# Development profile with a local PostgreSQL database
spring:
  profiles: dev
  thymeleaf:
    cache: false
  messages:
    cache-seconds: 10
  datasource:
    initialize: false
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/loltrollbuild
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: true
        format_sql: true
        generate_statistics: true
        hbm2ddl.auto:

---

# Unit testing profile with an embedded H2 database
spring:
  profiles: testing
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        generate_statistics: false
        hbm2ddl.auto: