# ======================
# Troll Build Properties
# ======================

riot:
  api:
    key: # from RIOT_API_KEY environment variable or -Driot.api.key argument property
    static-data:
      base-url: global.api.pvp.net/api/lol/static-data/{region}/v1.2
      param: api_key
      region: na
      scheme: https
      champions:  /champion
      champion:  /champion/{id}
      items: /item
      item: /item/{id}
      maps: /map
      summoner-spells: /summoner-spell
      summoner-spell: /summoner-spell/{id}
      versions: /versions
    ddragon:
      base-url: ddragon.leagueoflegends.com/cdn
      scheme: https
      champions-img: /{version}/img/champion/{championImgFull}
      champions-spell-img: /{version}/img/spell/{championSpellImgFull}
      champions-passive-img: /{version}/img/passive/{championPassiveImgFull}
      items-img: /{version}/img/item/{itemImgFull}
      maps-img: /{version}/img/map/{mapImgFull}
      summoner-spells-img: /{version}/img/spell/{summonerSpellImgFull}

# ======================
# Spring Boot Properties
# ======================

spring:
  # Spring active profile
  profiles.active: external
  # Data REST base URI
  data.rest.base-path: /api
  # Internalization
  messages.basename: i18n/messages
  # Resource handling
  resources.cache-period: 31556926
  # Thymeleaf
  thymeleaf.mode: HTML
  # Batch
  batch:
    initializer.enabled: false
    job.enabled: false
# Actuator
management.context-path: /admin/actuator

---

# Production profile with an embedded H2 database
spring:
  profiles: embedded
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: false
        generate_statistics: false
        hbm2ddl.auto:

---

# Production profile with an external PostgreSQL database
spring:
  profiles: external
  datasource:
    initialize: false
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: false
        format_sql: false
        generate_statistics: false
        hbm2ddl.auto:
  h2.console.enabled: false

---

# Development profile with a local PostgreSQL database
spring:
  profiles: dev
  datasource:
    initialize: false
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/loltrollbuild
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: true
        format_sql: false
        generate_statistics: false
        hbm2ddl.auto:
  h2.console.enabled: false

---

# Unit testing profile with an embedded H2 database
spring:
  profiles: testing
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: false
        generate_statistics: false
        hbm2ddl.auto: