= LeagueTrollBuild Spring Boot Backend

== Profiles
There are 4 database profiles:

external::
Production profile that is active by default and uses PostgreSQL along with environment variables to specify the
database credentials. Use the `LTB_DB_USERNAME`, `LTB_DB_PASSWORD`, `LTB_DB_URL` environment variables for the database credentials.

embedded::
Secondary production profile that uses an embedded H2 for quickly running the app locally without a PostgreSQL install.

dev::
Development profile that also uses PostgreSQL with the url: `jdbc:postgresql://localhost/loltrollbuild`

test::
Testing profile for https://github.com/junit-team/junit[JUnit 4] tests using H2.

In addition, there is one Riot API profile:

ddragon::
Data Dragon

To override an active profile, set the `spring.profiles.active` argument property such as:

 -Dspring.profiles.active=dev

Or using the environment variable `SPRING_PROFILES_ACTIVE`. Otherwise, if a profile is not specified, the `external`
and `ddragon` profiles will be active.

== Running the Backend locally
Create a run config that uses the `LeagueTrollBuildApplication` main class

Once the backend starts, view http://localhost:8080/api[localhost:8080/api] on your browser.

=== All Retrievals from Riot
Optionally, run with the following argument properties to trigger on startup the retrieval of the latest data (Items,
 Maps, Champions, Summoner Spells) from Riot's https://developer.riotgames.com/static-data.html[Data Dragon API] in
 order to perform a troll build of a Champion.

  -Dspring.batch.job.enabled=true -Dspring.batch.job.names=allRetrievalsJob

This is useful to avoid manual saving of data through the admin area. If data already exists in the database, a new
patch is out, and the retrievals job is run, then new data will be saved and absent data will be deleted.

=== API Documentation
To view the generated API guide, visit http://localhost:8080/docs/api-guide.html[localhost:8080/docs/api-guide.html].

To generate the API Documentation locally, run the asciidoctor Gradle task with the single test `ApiDocumentation`:

  asciidoctor -Dtest.single=ApiDocumentation

Then navigate to `/build/asciidoc/html5/api-guide.html` to view the generated API guide.

== Test Data
Run the `get-json-test-data.js` using node to get the latest static data from Riot for the integration tests to use.

  node get-json-test-data.js

This will overwrite existing `json` files in the `src/test/resources` folder. Format them using the IDE or an online service.
