= LeagueTrollBuild Spring Boot Backend

== Profiles
There are 4 database profiles:

external::
Production profile that is active by default and uses PostgreSQL along with environment variables to specify the
database credentials. Use the `LTB_DB_USERNAME`, `LTB_DB_PASSWORD`, `LTB_DB_URL` environment variables for the database credentials.

embedded::
Secondary production profile that uses an embedded H2 for quickly running the app locally without a PostgreSQL install.

dev::
Development profile that also uses PostgreSQL with the url: `jdbc:postgresql://localhost/loltrollbuild`

test::
Testing profile for https://junit.org/junit5/docs/current/user-guide/[JUnit 5] tests using H2.

To override an active profile, set the `spring.profiles.active` argument property such as:

 -Dspring.profiles.active=dev

Or by using the environment variable `SPRING_PROFILES_ACTIVE`.
Otherwise, if a profile is not specified, the `external` profile will be active.

== Running the Backend locally
Create a run config that uses the `LeagueTrollBuildApplication` main class

Optionally, pull the PostreSQL Docker image and run a PostreSQL container from the image to use as the app database:

  docker pull postgres:12.8
  docker run --name league-troll-build-pg -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=loltrollbuild -e POSTGRES_USER=postgres -p 5432:5432 -d postgres:12.8

Add then `LTB_DB_USERNAME=postgres`, `LTB_DB_PASSWORD=postgres`, `LTB_DB_URL=jdbc:postgresql://localhost/loltrollbuild` environment variables for the run config.

Once the backend starts, view http://localhost:8080/api[localhost:8080/api] on your browser.

=== All Retrievals from Riot
Optionally, run with the following argument properties to trigger on startup the retrieval of the latest data (Items,
Maps, Champions, Summoner Spells) from Riot's https://developer.riotgames.com/static-data.html[Data Dragon API] in
order to perform a troll build of a Champion.

  -Dspring.batch.job.enabled=true -Dspring.batch.job.names=allRetrievalsJob

Or using environment variables:

  SPRING_BATCH_JOB_ENABLED=true
  SPRING_BATCH_JOB_NAMES=allRetrievalsJob

If the database is new, it's recommended to run the `allRetrievalsJob`. But if data already exists in the database, a new
patch is out, and the retrievals job is run, then new data will be saved and absent data will be deleted.

=== API Documentation
To view the generated API guide, visit http://localhost:8080/docs/api-guide.html[localhost:8080/docs/api-guide.html].

To generate the API Documentation locally, run the `asciidoctor` Gradle task:

  ./gradlew backend:asciidoctor -x frontend:karmaTests

Then navigate to `/build/asciidoc/html5/api-guide.html` to view the generated API guide.

== Test Data
Run the `get-json-test-data.js` in the `scripts` folder using node.js to get the latest static data from Riot for the integration tests to use.

  node scripts/get-json-test-data.js

This will overwrite existing `json` files in the `src/test/resources` folder if the latest saved version of the test jsons
is different from the latest Riot version.

Note, if the two versions are the same, then the script will exit.
This behavior can be overridden with the `--force` flag.
