# ======================
# Troll Build Properties
# ======================

riot:
  ddragon:
    base-url: https://ddragon.leagueoflegends.com
    locale: en_US
    champions: /cdn/{version}/data/{locale}/champion.json
    champion: /cdn/{version}/data/{locale}/champion/{id}.json
    champions-img: /cdn/{version}/img/champion/{championImgFull}
    champions-spell-img: /cdn/{version}/img/spell/{championSpellImgFull}
    champions-passive-img: /cdn/{version}/img/passive/{championPassiveImgFull}
    items: /cdn/{version}/data/{locale}/item.json
    items-img: /cdn/{version}/img/item/{itemImgFull}
    maps: /cdn/{version}/data/{locale}/map.json
    maps-img: /cdn/{version}/img/map/{mapImgFull}
    summoner-spells: /cdn/{version}/data/{locale}/summoner.json
    summoner-spells-img: /cdn/{version}/img/spell/{summonerSpellImgFull}
    versions: /api/versions.json

api:
  base-path: /api

batch:
  task-executor:
    core-pool-size: 5
    max-pool-size: 10

# ======================
# Spring Boot Properties
# ======================

spring:
  # Spring profiles
  profiles:
    active: external
    include: ddragon
  # Internalization
  messages.basename: i18n/messages
  # Batch
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  # Jackson
  jackson:
    deserialization:
      read_unknown_enum_values_using_default_value: true
  # JPA
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
  # Data
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  # Web
  web:
    # Resources
    resources:
      add-mappings: false
  # MVC
  mvc:
    formcontent:
      filter:
        enabled: false
# Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: env, flyway, health, metrics, scheduledtasks
# Server
server:
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true

---

# Production profile with an embedded H2 database
spring:
  config.activate.on-profile: embedded

---

# Production profile with an external PostgreSQL database
spring:
  config.activate.on-profile: external
  datasource:
    url: ${LTB_DB_URL}
    username: ${LTB_DB_USERNAME}
    password: ${LTB_DB_PASSWORD}
  h2:
    console:
      enabled: false

---

# Development profile with a local PostgreSQL database
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost/loltrollbuild
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  h2:
    console:
      enabled: false

---

# Unit testing profile with an embedded H2 database
spring:
  config.activate.on-profile: testing
  jpa:
    show-sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  # Cache
  cache:
    type: simple
# Jackson
  jackson:
    serialization:
      indent_output: true
