# ======================
# Troll Build Properties
# ======================

riot:
  ddragon:
    base-url: https://ddragon.leagueoflegends.com
    locale: en_US
    champions: /cdn/{version}/data/{locale}/champion.json
    champion: /cdn/{version}/data/{locale}/champion/{id}.json
    champions-img: /cdn/{version}/img/champion/{championImgFull}
    champions-spell-img: /cdn/{version}/img/spell/{championSpellImgFull}
    champions-passive-img: /cdn/{version}/img/passive/{championPassiveImgFull}
    items: /cdn/{version}/data/{locale}/item.json
    items-img: /cdn/{version}/img/item/{itemImgFull}
    maps: /cdn/{version}/data/{locale}/map.json
    maps-img: /cdn/{version}/img/map/{mapImgFull}
    summoner-spells: /cdn/{version}/data/{locale}/summoner.json
    summoner-spells-img: /cdn/{version}/img/spell/{summonerSpellImgFull}
    versions: /api/versions.json

api:
  base-path: /api

# ======================
# Spring Boot Properties
# ======================

spring:
  # Spring active profile
  profiles.active: external, ddragon
  # Internalization
  messages.basename: i18n/messages
  # Batch
  batch:
    initialize-schema: never
    job:
      enabled: false
  # Jackson
  jackson:
    deserialization:
      fail_on_unknown_properties: false
  # JPA
  jpa:
    open-in-view: false
  # Resources
  resources:
    cache:
      cachecontrol:
        max-age: 31536000s # (1 year)
  # JMX
  jmx:
    enabled: false
  # MVC
  mvc:
    formcontent:
      filter:
        enabled: false
    hiddenmethod:
      filter:
        enabled: false
# Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: flyway, metrics
# Server
server:
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true

---

# Production profile with an embedded H2 database
spring:
  profiles: embedded
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:
        temp.use_jdbc_metadata_defaults: false

---

# Production profile with an external PostgreSQL database
spring:
  profiles: external
  datasource:
    url: ${LTB_DB_URL}
    username: ${LTB_DB_USERNAME}
    password: ${LTB_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: false
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:
        temp.use_jdbc_metadata_defaults: false

---

# Development profile with a local PostgreSQL database
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost/loltrollbuild
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: true
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:
        temp.use_jdbc_metadata_defaults: false

---

# Unit testing profile with an embedded H2 database
spring:
  profiles: testing
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: false
        generate_statistics: false
        id.new_generator_mappings: true
        hbm2ddl.auto:
        temp.use_jdbc_metadata_defaults: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  # Cache
  cache:
    type: simple
# Jackson
  jackson:
    serialization:
      indent_output: true
