-- Builds
DELETE FROM BUILD;

-- Champions
DELETE FROM CHAMPION_TAG;
DELETE FROM CHAMPION_SPELL_IMAGE;
DELETE FROM CHAMPION_SPELL_COST;
DELETE FROM CHAMPION_SPELL_COOLDOWN;
DELETE FROM CHAMPION_SPELL_RANGE;
DELETE FROM CHAMPION_SPELL;
DELETE FROM CHAMPION_INFO;
DELETE FROM CHAMPION_PASSIVE_IMAGE;
DELETE FROM CHAMPION_PASSIVE;
DELETE FROM CHAMPION_IMAGE;
DELETE FROM CHAMPION;

-- Items
DELETE FROM ITEM_FROM;
DELETE FROM ITEM_INTO;
DELETE FROM ITEM_TAG;
DELETE FROM ITEM_MAP;
DELETE FROM ITEM_GOLD;
DELETE FROM ITEM_IMAGE;
DELETE FROM ITEM;

-- Maps
DELETE FROM MAP_IMAGE;
DELETE FROM MAP;

-- Summoner Spells
DELETE FROM SUMMONER_SPELL_COOLDOWN;
DELETE FROM SUMMONER_SPELL_MODE;
DELETE FROM SUMMONER_SPELL_IMAGE;
DELETE FROM SUMMONER_SPELL;

-- Versions
DELETE FROM VERSION;
