CREATE TABLE SUMMONER_SPELL_COOLDOWN (
  SUMMONER_SPELL_ID INT,
  COOLDOWN          INT,
  PRIMARY KEY (SUMMONER_SPELL_ID, COOLDOWN),
  FOREIGN KEY (SUMMONER_SPELL_ID) REFERENCES SUMMONER_SPELL (ID)
);