CREATE TABLE AUTHORITIES (
  USERNAME  VARCHAR(50) NOT NULL,
  AUTHORITY VARCHAR(50) NOT NULL,
  CONSTRAINT FX_AUTHORITIES_USERS FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME)
);
CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERNAME, AUTHORITY);

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('admin', 'ROLE_ADMIN');