CREATE TABLE ITEM (
  ID                 INT PRIMARY KEY,
  NAME               VARCHAR(255),
  ITEM_GROUP         VARCHAR(255),
  CONSUMED           BOOLEAN,
  DESCRIPTION        TEXT,
  REQUIRED_CHAMPION  VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP NOT NULL
);