CREATE TABLE SUMMONER_SPELL (
  ID                 INT PRIMARY KEY,
  NAME               VARCHAR(255) NOT NULL,
  DESCRIPTION        VARCHAR(255) NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP    NOT NULL
);