CREATE TABLE CHAMPION (
  ID                 INT PRIMARY KEY,
  VERSION            INT NOT NULL,
  CHAMPION_KEY       VARCHAR(255) NOT NULL,
  NAME               VARCHAR(255) NOT NULL,
  TITLE              VARCHAR(255) NOT NULL,
  PARTYPE            VARCHAR(255) NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP    NOT NULL
);