CREATE TABLE ITEM (
  ID                INT PRIMARY KEY,
  NAME              VARCHAR(255) NOT NULL,
  ITEM_GROUP        VARCHAR(255),
  CONSUMED          BOOLEAN,
  DESCRIPTION       TEXT         NOT NULL,
  REQUIRED_CHAMPION VARCHAR(255)
);