CREATE TABLE USERS (
  USERNAME VARCHAR(50)  PRIMARY KEY,
  PASSWORD VARCHAR(255) NOT NULL,
  ENABLED  BOOLEAN      NOT NULL
);

-- password is "password" (no quotes)
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED)
VALUES ('admin', '$2a$08$tm.em86uS8vNBca1Ljlpv.x9QU122s8PoSWiL21vNNUJWhCWbs8tW', TRUE);